[theme]
base = "light"
primaryColor = "#4B4FC4"
backgroundColor = "#EDF1EF"
secondaryBackgroundColor = "#E1E8E6"
textColor = "#10282E"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
